name: Release

on:
  push:
    branches:
      - master
    paths:
      - Cargo.toml

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Get crate version
        id: version
        run: |
          echo "VERSION=$(grep '^version' Cargo.toml | head -1 | sed 's/version = \"//; s/\"//')" >> $GITHUB_OUTPUT

      - name: Build release binary
        run: cargo build --release

      - name: Create Git tag
        run: |
          git tag v${{ steps.version.outputs.VERSION }}
          git push origin v${{ steps.version.outputs.VERSION }}

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.version.outputs.VERSION }}
          name: Release v${{ steps.version.outputs.VERSION }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload binary to release
        uses: softprops/action-gh-release@v2
        with:
          files: target/release/<your-binary-name>
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
